"""Render a `DagPlan` into Airflow 3.2 DAG source code.

Airflow-3-specific choices (these are exactly the things a 2->3 upgrade breaks):
  * `schedule=` — `schedule_interval` was removed.
  * Operators come from the `standard` provider, not `airflow.operators.*`.
  * TaskGroup / DAG imported from the Task SDK (`airflow.sdk`).
  * No SLA — removed in Airflow 3. Timeouts use `execution_timeout`; the alarm
    semantics live in Datadog monitors instead.
"""

from __future__ import annotations

from .translator import DagPlan, TaskPlan

_DOCSTRING = '''"""AUTO-GENERATED by jil2dag from AutoSys JIL. Do not edit by hand.

Source jobs: {sources}
Regenerate with: jil2dag migrate --input <jil> --output <dags>
"""'''


def _build_header(plan: DagPlan) -> str:
    """Emit only the imports this DAG actually uses (keeps ruff F401 clean)."""
    ops = {t.operator for t in plan.tasks}
    needs_timeout = any(t.execution_timeout_min for t in plan.tasks)
    needs_external = any(t.external_waits for t in plan.tasks)
    needs_group = bool(plan.groups)

    lines = [
        _DOCSTRING.format(sources=", ".join(plan.source_jobs)),
        "from __future__ import annotations",
        "",
    ]
    if needs_timeout:
        lines += ["from datetime import timedelta", ""]
    lines.append("import pendulum")

    # isort order: plain imports, then `from` imports alphabetically by module.
    if "BashOperator" in ops or "SSHOperator" in ops:
        lines.append("from airflow.providers.standard.operators.bash import BashOperator")
    if needs_external:
        lines.append(
            "from airflow.providers.standard.sensors.external_task import ExternalTaskSensor"
        )
    if "FileSensor" in ops:
        lines.append("from airflow.providers.standard.sensors.filesystem import FileSensor")

    sdk = ["DAG"] + (["TaskGroup"] if needs_group else [])
    lines.append(f"from airflow.sdk import {', '.join(sdk)}")

    if "SSHOperator" in ops:
        lines += [
            "",
            "try:",
            "    from airflow.providers.ssh.operators.ssh import SSHOperator",
            "except ImportError:  # ssh provider optional in local/dev",
            "    SSHOperator = BashOperator  # type: ignore[assignment,misc]",
        ]
    lines += ["", "from datadog_callbacks import DEFAULT_ARGS, dag_tags"]
    return "\n".join(lines)

_OP_RENDER = {
    "BashOperator": lambda k: f'BashOperator(task_id={k["task_id"]!r}, '
                              f'bash_command={k.get("bash_command", "true")!r}{k["_common"]})',
    "SSHOperator": lambda k: f'SSHOperator(task_id={k["task_id"]!r}, '
                             f'ssh_conn_id={k.get("ssh_conn_id", "ssh_default")!r}, '
                             f'command={k.get("command", "true")!r}{k["_common"]})',
    "FileSensor": lambda k: f'FileSensor(task_id={k["task_id"]!r}, '
                            f'filepath={k.get("filepath", "")!r}, '
                            f'poke_interval={k.get("poke_interval", 60)}, mode="reschedule"{k["_common"]})',
}


def _common_suffix(task: TaskPlan) -> str:
    parts = []
    if task.trigger_rule != "all_success":
        parts.append(f"trigger_rule={task.trigger_rule!r}")
    if task.execution_timeout_min:
        parts.append(f"execution_timeout=timedelta(minutes={task.execution_timeout_min})")
    return (", " + ", ".join(parts)) if parts else ""


def _render_task(task: TaskPlan, indent: str) -> str:
    kwargs = dict(task.kwargs)
    kwargs["task_id"] = task.task_id
    kwargs["_common"] = _common_suffix(task)
    body = _OP_RENDER[task.operator](kwargs)
    return f"{indent}{task.task_id} = {body}"


def emit(plan: DagPlan) -> str:
    lines: list[str] = [_build_header(plan)]

    schedule = repr(plan.schedule) if plan.schedule else "None"
    tz = f'pendulum.timezone({plan.timezone!r})' if plan.timezone else '"UTC"'

    lines.append("")
    lines.append("with DAG(")
    lines.append(f"    dag_id={plan.dag_id!r},")
    lines.append(f"    schedule={schedule},")
    lines.append(f'    start_date=pendulum.datetime(2025, 1, 1, tz={tz}),')
    lines.append("    catchup=False,")
    lines.append("    default_args=DEFAULT_ARGS,")
    lines.append(f"    tags=dag_tags({plan.source_jobs!r}),")
    lines.append(") as dag:")

    grouped = [t for t in plan.tasks if t.group]
    ungrouped = [t for t in plan.tasks if not t.group]

    # External waits become sensor tasks declared at DAG scope.
    external_sensor_ids: dict[tuple[str, str], str] = {}
    for t in plan.tasks:
        for dag_id, task_id in t.external_waits:
            sid = f"wait_{dag_id}_{task_id}"
            external_sensor_ids[(dag_id, task_id)] = sid

    for (dag_id, task_id), sid in external_sensor_ids.items():
        lines.append(
            f'    {sid} = ExternalTaskSensor(task_id={sid!r}, '
            f'external_dag_id={dag_id!r}, external_task_id={task_id!r}, '
            f'mode="reschedule", poke_interval=60)'
        )

    # TaskGroup(s) for boxes.
    for group in plan.groups:
        lines.append(f'    with TaskGroup(group_id={group!r}) as {group}:')
        members = [t for t in grouped if t.group == group]
        if not members:
            lines.append("        pass")
        for t in members:
            lines.append(_render_task(t, "        "))
        # intra-group edges
        for t in members:
            for up in t.upstreams:
                lines.append(f"        {up} >> {t.task_id}")

    for t in ungrouped:
        lines.append(_render_task(t, "    "))
    for t in ungrouped:
        for up in t.upstreams:
            lines.append(f"    {up} >> {t.task_id}")

    # external edges
    for t in plan.tasks:
        for dag_id, task_id in t.external_waits:
            sid = external_sensor_ids[(dag_id, task_id)]
            target = t.group if t.group else t.task_id
            lines.append(f"    {sid} >> {target}")

    lines.append("")
    return "\n".join(lines)
