"""AUTO-GENERATED by jil2dag from AutoSys JIL. Do not edit by hand.

Source jobs: EOD_EXTRACT, EOD_LOAD, EOD_RECON_ALERT, EOD_REPRICE, EOD_TRANSFORM, EOD_VALIDATE, EOD_WAIT_FEED
Regenerate with: jil2dag migrate --input <jil> --output <dags>
"""
from __future__ import annotations

from datetime import timedelta

import pendulum
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.sensors.filesystem import FileSensor
from airflow.sdk import DAG, TaskGroup

try:
    from airflow.providers.ssh.operators.ssh import SSHOperator
except ImportError:  # ssh provider optional in local/dev
    SSHOperator = BashOperator  # type: ignore[assignment,misc]

from datadog_callbacks import DEFAULT_ARGS, dag_tags

with DAG(
    dag_id='eod_settlement',
    schedule='30 18 * * 1,2,3,4,5',
    start_date=pendulum.datetime(2025, 1, 1, tz=pendulum.timezone('America/New_York')),
    catchup=False,
    default_args=DEFAULT_ARGS,
    tags=dag_tags(['EOD_EXTRACT', 'EOD_LOAD', 'EOD_RECON_ALERT', 'EOD_REPRICE', 'EOD_TRANSFORM', 'EOD_VALIDATE', 'EOD_WAIT_FEED']),
) as dag:
    with TaskGroup(group_id='eod_settlement') as eod_settlement:
        eod_wait_feed = FileSensor(task_id='eod_wait_feed', filepath='/data/feeds/positions_$$DATE.csv', poke_interval=60, mode="reschedule")
        eod_extract = SSHOperator(task_id='eod_extract', ssh_conn_id='ssh_prod-etl-01', command='/opt/batch/extract_positions.sh ')
        eod_validate = SSHOperator(task_id='eod_validate', ssh_conn_id='ssh_prod-etl-01', command='/opt/batch/validate.sh --strict', execution_timeout=timedelta(minutes=30))
        eod_transform = SSHOperator(task_id='eod_transform', ssh_conn_id='ssh_prod-etl-02', command='/opt/batch/transform.sh ')
        eod_reprice = SSHOperator(task_id='eod_reprice', ssh_conn_id='ssh_prod-etl-02', command='/opt/batch/reprice.sh ')
        eod_load = BashOperator(task_id='eod_load', bash_command='/opt/batch/load_warehouse.sh ', trigger_rule='all_done')
        eod_recon_alert = BashOperator(task_id='eod_recon_alert', bash_command='/opt/batch/page_oncall.sh --reason recon-fail', trigger_rule='all_failed')
        eod_wait_feed >> eod_extract
        eod_extract >> eod_validate
        eod_validate >> eod_transform
        eod_validate >> eod_reprice
        eod_transform >> eod_load
        eod_reprice >> eod_load
        eod_load >> eod_recon_alert
