"""AUTO-GENERATED by jil2dag from AutoSys JIL. Do not edit by hand.

Source jobs: EOD_REG_REPORT
Regenerate with: jil2dag migrate --input <jil> --output <dags>
"""
from __future__ import annotations

import pendulum
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.sensors.external_task import ExternalTaskSensor
from airflow.sdk import DAG, TaskGroup

from datadog_callbacks import DEFAULT_ARGS, dag_tags

with DAG(
    dag_id='eod_reporting',
    schedule='0 20 * * 1,2,3,4,5',
    start_date=pendulum.datetime(2025, 1, 1, tz=pendulum.timezone('America/New_York')),
    catchup=False,
    default_args=DEFAULT_ARGS,
    tags=dag_tags(['EOD_REG_REPORT']),
) as dag:
    wait_eod_settlement_eod_load = ExternalTaskSensor(task_id='wait_eod_settlement_eod_load', external_dag_id='eod_settlement', external_task_id='eod_load', mode="reschedule", poke_interval=60)
    wait_eod_settlement_eod_recon_alert = ExternalTaskSensor(task_id='wait_eod_settlement_eod_recon_alert', external_dag_id='eod_settlement', external_task_id='eod_recon_alert', mode="reschedule", poke_interval=60)
    with TaskGroup(group_id='eod_reporting') as eod_reporting:
        eod_reg_report = BashOperator(task_id='eod_reg_report', bash_command='/opt/batch/reg_report.sh ')
    wait_eod_settlement_eod_load >> eod_reporting
    wait_eod_settlement_eod_recon_alert >> eod_reporting
